# Generated by Django 5.0.2 on 2024-03-29 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DtcCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ErrCompId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('eADP', models.CharField(max_length=100)),
                ('project_code', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('simulation_type', models.CharField(max_length=100)),
                ('test_Scenario_ID', models.CharField(max_length=100)),
                ('sw_version', models.CharField(max_length=10)),
                ('weather', models.CharField(max_length=50)),
                ('road_type', models.CharField(max_length=50)),
                ('sun_status', models.CharField(max_length=50)),
                ('temperature', models.IntegerField()),
                ('dtc_code', models.ManyToManyField(to='registerapp.dtccode')),
                ('err_comp_id', models.ManyToManyField(to='registerapp.errcompid')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
