# Generated by Django 5.0.2 on 2024-04-12 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, unique=True)),
                ('test_case_ids', models.JSONField()),
                ('usernames', models.JSONField()),
                ('eADP', models.CharField(max_length=100)),
                ('project_code', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('sw_version', models.CharField(max_length=100)),
                ('weather', models.CharField(max_length=100)),
                ('road_type', models.CharField(max_length=50)),
                ('road_status', models.CharField(max_length=50)),
                ('sun_status', models.CharField(max_length=50)),
                ('test_mode', models.CharField(max_length=50)),
                ('temperature', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
